### ISSUE TITLE
请教如何启动

### ISSUE THREAD

**Issue by DaoshunShi** [huisongyang/fileserver#1]
大佬，请问您的这个项目如何启动。

我在idea中修改了runServer.bat 中的 root.dir.path
但是在程序中没有读到这个配置
报错为：Exception in thread "main" java.lang.Exception: root.dir.path不存在

然后我有试了一下在Server.java Client.java中写入root.dir.path
可以启动Server，但client无法成功连接到server
报错为：Exception in thread "main" java.net.ConnectException: Connection refused: no further information: /127.0.0.1:9999

请问大佬您的这个项目有哪些地方需要配置一下吗

**Comment by huisongyang** [comment]
配置好root.dir.path就可以了的，不需要其他配置，你可以看下server启动后，9999端口是不是监听状态，如果客户端不是在一个机器上跑的话，你关下防火墙。

**Comment by DaoshunShi** [comment]
我修改过了root.dir.path，然后在IDEA中运行Server.java，仍然是找不到runServer
报错信息为：
`Exception in thread "main" java.lang.Exception: root.dir.path不存在
	at com.yhs.fileserver.core.FileScan.scanningAndWrite(FileScan.java:102)
	at com.yhs.fileserver.server.Server.main(Server.java:38)

Process finished with exit code 1`
这个是因为Server.java读不到root.dir.path吗

**Comment by huisongyang** [comment]
编译后，你可以运行runServer.bat这个文件，根据redeme讲解的过程来

**Comment by DaoshunShi** [comment]
哦哦 明白了
我漏了打包这步 mvn package
谢谢大佬！
